---
- hosts: all
  sudo: true
  vars:
    document_root: /vagrant

  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes

  # Note that roles are run before Tasks
  roles:
    - webserver
    - database

# 'vagrant provision' may be run to apply only needed changes