---
- name: install apache
  apt: name=apache2 state=present
- name: Copy virtual host config
  template: 
    src=virtual-hosts.conf.j2 
    dest=/etc/apache2/sites-available/vagrant.conf

- name: Remove default virtual host
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent

- name: Enable new vagrant host
  file:
    src=/etc/apache2/sites-available/vagrant.conf
    dest=/etc/apache2/sites-enabled/vagrant.conf
    state=link

# Now we run service module to reload apache
- name: reload apache
  service: name=apache2 state=reloaded